# Generated by Django 5.0.7 on 2024-07-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
